import{useEffect,useRef,useState}from'react';
import{realms,type Life}from'./game';
import{playSound,setSound,soundEnabled,unlockSound}from'./sound';
export function SoundToggle(){const[on,setOn]=useState(soundEnabled);return <button className="sound-toggle" aria-label={on?'Mute sound effects':'Enable sound effects'} aria-pressed={on} onClick={()=>{setSound(!on);setOn(!on);}}>{on?'♪ Sound on':'♪ Sound off'}</button>}
export function Feedback({s}:{s:Life}){const prev=useRef(s),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),ref=useRef<HTMLDivElement>(null);const[notice,show]=useState<{id:number;kind:string;title:string;detail:string}|null>(null);const id=useRef(0);
 useEffect(()=>{document.addEventListener('pointerdown',unlockSound);document.addEventListener('keydown',unlockSound);return()=>{document.removeEventListener('pointerdown',unlockSound);document.removeEventListener('keydown',unlockSound);clearTimeout(timer.current);};},[]);
 useEffect(()=>{const p=prev.current;prev.current=s;let kind='',title='',detail='';if(s.realm>p.realm){kind='success';title='Breakthrough';detail=realms[s.realm];}else if(s.log.length>p.log.length&&s.log[0]?.text.includes('Your breakthrough fails')){kind='failure';title='Not yet';detail='Your meridians need time to recover.';}else if(s.age>p.age){kind='age';title='Age '+s.age;detail=s.silver>p.silver?'+'+(s.silver-p.silver)+' silver · A new chapter':'A new chapter begins';}else if((s.memories.careerRank??0)>(p.memories.careerRank??0)){kind='success';title='Promoted';detail='Your dedication is paying off.';}else if(s.energy<p.energy){kind='action';title='Progress made';detail=s.memories.careerPerformance!==p.memories.careerPerformance?'Your working life evolves.':'Practice shapes your path.';}if(kind){if(s.log.some(e=>e.age===s.age&&e.text.startsWith('Promotion!'))&&s.age>p.age){title='Promotion · Age '+s.age;detail='Your salary rises from next year.';kind='success';}clearTimeout(timer.current);show({id:++id.current,kind,title,detail});playSound(kind as 'age'|'success'|'failure'|'action');timer.current=setTimeout(()=>show(null),kind==='success'?2300:1500);}},[s]);
 useEffect(()=>{if(notice){try{ref.current?.showPopover();}catch{}}},[notice]);
 return notice?<div key={notice.id} ref={ref} popover="manual" className={'life-feedback '+notice.kind} role="status"><div className="feedback-ring" aria-hidden="true"/><span aria-hidden="true" className="feedback-symbol">{notice.kind==='success'?'✧':notice.kind==='failure'?'◇':'+'}</span><strong>{notice.title}</strong><small>{notice.detail}</small></div>:null;
}

