import{draw,randomName,npcPool,personalityPool,traitPool,backgroundPool,backgroundEventPool,mainEventPool}from'./pools.ts';
export type Stat = 'strength'|'intelligence'|'charisma'|'constitution'|'perception'|'willpower'|'luck';
export type NpcDetails={id:string;gender?:'Male'|'Female';portrait:number;portraitSet?:number;job?:string;background?:string;specialTrait?:string;friend:boolean;trait:string;goal:string;root:string;talent:number;qi:number;wealth:number;health:number;stats:{strength:number;intelligence:number;willpower:number};memories:string[]};
export type Person={details?:NpcDetails;name:string;role:string;bond:number;age:number;realm:number;alive:boolean};
export type Choice={label:string;hint:string;effect:Partial<Record<'health'|'silver'|'qi'|'reputation'|'bond',number>>;risk?:number;memory?:string};
export type Event={id:string;title:string;text:string;choices:Choice[]};
export type Life={version:1;childAppearance:number;job:string|null;appearance:number|null;school:{enrolled:boolean;graduated:boolean;grades:number;conduct:number};inventory:Record<string,number>;equipped:string|null;master:string|null;clan:string|null;favor:number;energy:number;idle:boolean;lastTick:number;lastEventAge:number;village:string;gender:string;name:string;age:number;health:number;silver:number;qi:number;realm:number;reputation:number;root:string;talent:number;trait:string;family:string;stats:Record<Stat,number>;people:Person[];log:{age:number;text:string}[];event:Event|null;memories:Record<string,number>;dead:boolean;cause:string;years:number};
export const realms=['Mortal','Qi Gathering','Foundation Establishment','Core Formation','Nascent Soul'];
const pick=<T,>(a:T[],r:()=>number)=>a[Math.floor(r()*a.length)];
export function birth(r=Math.random):Life {const stats={} as Record<Stat,number>;for(const k of ['strength','intelligence','charisma','constitution','perception','willpower','luck'] as Stat[])stats[k]=5+Math.floor(r()*16);const family=pick(families.map(f=>f.name),r);return startLife({version:1,childAppearance:0,job:null,appearance:null,school:{enrolled:false,graduated:false,grades:50,conduct:80},inventory:{},equipped:null,master:null,clan:null,favor:0,energy:3,idle:false,lastTick:Date.now(),lastEventAge:-2,village:pick(['Blackwind Village','Jadebrook Village','Pinecloud Village','Redstone Village'],r),gender:'Unspecified',name:randomName(r),age:0,health:100,silver:families.find(f=>f.name===family)!.silver,qi:0,realm:0,reputation:0,root:pick(['Fire','Water','Wood','Earth','Metal'],r),talent:1+Math.floor(r()*3),trait:pick(['Patient','Ambitious','Kind','Disciplined','Reckless'],r),family,stats,people:[{name:pick(['Liu Yue','Shen Lian','Mei Rong','Su Lan'],r),role:'Mother',bond:80,age:24+Math.floor(r()*12),realm:0,alive:true},{name:'Chen Tao',role:'Childhood friend',bond:50,age:0,realm:0,alive:true}],log:[],event:null,memories:{},dead:false,cause:'',years:0},r);}
const add=(s:Life,text:string)=>s.log.unshift({age:s.age,text});
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
function finish(s:Life,cause:string){s.dead=true;s.cause=cause;s.event=null;add(s,'Your life ends. '+cause);}
export function threshold(s:Life){return 40+s.realm*50;}
function baseEventFor(s:Life,r=Math.random):Event{
if(s.memories.saved!==undefined&&s.age>=s.memories.saved+5&&!s.memories.repaid)return{id:'repaid',title:'A debt remembered',text:'The wounded stranger you once helped returns wearing the robes of an elder. He has not forgotten your kindness.',choices:[{label:'Accept his guidance',hint:'+35 qi · +10 reputation',effect:{qi:35,reputation:10},memory:'repaid'},{label:'Ask for help with your household',hint:'+70 silver',effect:{silver:70},memory:'repaid'}]};
if(s.age<6)return{id:'child',title:'Small beginnings',text:'The village wakes beneath a veil of mountain mist. Every ordinary day quietly shapes who you will become.',choices:[{label:'Stay close to your family',hint:'+5 health · +6 family bond',effect:{health:5,bond:6}},{label:'Explore the village paths',hint:'+3 reputation · small risk of a scraped knee',effect:{reputation:3},risk:.08}]};
if(s.age<12)return{id:'school',title:'An old scholar’s invitation',text:'An itinerant scholar offers to teach the village children. At home, your family could also use another pair of hands.',choices:[{label:'Listen to the scholar',hint:'+8 qi · prepare your mind',effect:{qi:8}},{label:'Help with the harvest',hint:'+10 silver · +4 family bond',effect:{silver:10,bond:4}},{label:'Play with Chen Tao',hint:'+10 friendship',effect:{bond:10}}]};
const events:Event[]=[{id:'stranger',title:'A stranger in the reeds',text:'Beside the river, a wounded cultivator clutches a broken jade token. His pursuers are nowhere to be seen. For now.',choices:[{label:'Tend to his wounds',hint:'Spend 5 silver · a kindness may be remembered',effect:{silver:-5,reputation:6},memory:'saved'},{label:'Take his abandoned purse',hint:'+24 silver · −8 reputation',effect:{silver:24,reputation:-8},memory:'stolen'},{label:'Return to the village',hint:'Leave the matter behind',effect:{}}]},
{id:'market',title:'The traveling apothecary',text:'A merchant unfolds a cloth of medicinal herbs. A recovery draught could mend your injuries, if you can afford it.',choices:[{label:'Buy a recovery draught',hint:'−18 silver · +35 health',effect:{silver:-18,health:35}},{label:'Trade herbs you collected',hint:'+12 silver',effect:{silver:12}},{label:'Ask about spiritual herbs',hint:'+8 qi',effect:{qi:8}}]},
{id:'rival',title:'Pride in the courtyard',text:'Chen Tao challenges your understanding of the martial path in front of the village. The crowd waits for your reply.',choices:[{label:'Exchange ideas respectfully',hint:'+8 friendship · +8 qi',effect:{bond:8,qi:8}},{label:'Humiliate him',hint:'+9 reputation · −25 friendship',effect:{reputation:9,bond:-25},memory:'grudge'},{label:'Walk away',hint:'+3 health',effect:{health:3}}]},
{id:'caravan',title:'A road beyond the valley',text:'A caravan needs help crossing the mountain pass. The pay is good, but bandits have been seen along the road.',choices:[{label:'Guard the caravan',hint:'+30 silver · risk of injury',effect:{silver:30,reputation:4},risk:.3},{label:'Load supplies in the village',hint:'+10 silver',effect:{silver:10}},{label:'Spend the day recovering',hint:'+12 health',effect:{health:12}}]},
{id:'shrine',title:'Silence at the mountain shrine',text:'Rain taps against the abandoned shrine. A faded inscription speaks of a mind as still as an untroubled lake.',choices:[{label:'Study the inscription',hint:'+14 qi',effect:{qi:14}},{label:'Repair the shrine',hint:'+7 reputation · −4 silver',effect:{reputation:7,silver:-4}},{label:'Meditate until dawn',hint:'+22 qi · risk of exhaustion',effect:{qi:22},risk:.2}]}];
if(s.memories.grudge!==undefined&&s.age>=s.memories.grudge+8&&!s.memories.confronted)return{id:'confronted',title:'The weight of old words',text:'Chen Tao has never forgotten his public humiliation. Now a cultivator, he demands repayment for the insult.',choices:[{label:'Offer compensation',hint:'−30 silver · +15 friendship',effect:{silver:-30,bond:15},memory:'confronted'},{label:'Stand your ground',hint:'Risk serious injury · −10 friendship',effect:{bond:-10},risk:.7,memory:'confronted'},{label:'Apologize before the village',hint:'−12 reputation · +10 friendship',effect:{reputation:-12,bond:10},memory:'confronted'}]};
return pick([...events,...mainEventPool].filter(e=>e.id!=='stranger'||s.memories.saved===undefined),r);
}
export type Action='age'|'cultivate'|'work'|'rest'|'visit'|'breakthrough';
export function act(old:Life,action:Action,r=Math.random):Life {if(old.dead||old.event)return old;const s=structuredClone(old);if(action==='breakthrough'){if(s.age<12||s.realm>=4||s.qi<threshold(s))return old;s.qi-=threshold(s);const chance=Math.min(.9,.4+s.talent*.1+s.stats.willpower/100+(s.health>70?.08:-.12));if(r()<chance){s.realm++;add(s,'Breakthrough! You enter '+realms[s.realm]+'.');}else{s.health-=22;add(s,'Your breakthrough fails. Your meridians need time to recover.');}if(s.health<=0)finish(s,'Cultivation deviation');return s;}
if(s.age<12&&action!=='age')return old;
if(action==='cultivate'){const gain=Math.round((5+s.talent*4+Math.floor(s.stats.willpower/4))*multiplier(s));s.qi+=gain;s.health-=3;add(s,'You cultivate in seclusion, gaining '+gain+' qi.');}
if(action==='work'){s.silver+=12+Math.floor(s.stats.charisma/3);s.health-=2;add(s,'You earn silver helping the village traders.');}
if(action==='rest'){s.health=clamp(s.health+18);add(s,'You rest beneath the plum trees and recover your strength.');}
if(action==='visit'){s.people.filter(p=>p.alive).forEach(p=>p.bond=clamp(p.bond+9));add(s,'Shared tea and familiar stories deepen your connections.');}
const employment=jobs.find(j=>j.id===s.job);s.age++;s.years++;if(employment)careerYear(s);schoolYear(s,r);s.energy=3;s.lastTick=Date.now();for(const p of s.people){p.details=npcDetails(p);if(!p.alive)continue;p.age++;npcYear(p,s);if(p.age>75&&r()<.12){p.alive=false;add(s,p.name+' has passed away.');}}
const lifespan=75+s.realm*45; if(s.age>55)s.health-=3+Math.floor((s.age-55)/(15+s.realm*10));
if(s.health<=0)finish(s,'Your injuries and declining health overcome you.');else if(s.age>=lifespan)finish(s,'You reach the end of your natural lifespan.');else{s.health=clamp(s.health);background(s,r);const due=(s.memories.saved!==undefined&&s.age>=s.memories.saved+5&&!s.memories.repaid)||(s.memories.grudge!==undefined&&s.age>=s.memories.grudge+8&&!s.memories.confronted);if(due||(s.age-s.lastEventAge>1&&r()<.3)){s.event=eventFor(s,r);s.lastEventAge=s.age;}} return s;
}
export function choose(old:Life,index:number,r=Math.random):Life {if(old.dead||!old.event)return old;const c=old.event.choices[index];if(!c||old.silver+(c.effect.silver??0)<0)return old;const s=structuredClone(old);for(const k of ['health','silver','qi','reputation'] as const)s[k]+=c.effect[k]??0;if(c.effect.bond)s.people.filter(p=>p.alive&&(old.event?.id==='child'?['Family','Mother','Father'].includes(p.role):!['Family','Mother','Father'].includes(p.role))).forEach(p=>p.bond=clamp(p.bond+c.effect.bond!));if(c.memory)s.memories[c.memory]=s.age;add(s,old.event.title+': '+c.label+'.');if(c.risk&&r()<c.risk){s.health-=20+Math.floor(r()*20);add(s,'The encounter leaves you injured.');}s.health=clamp(s.health);s.event=null;if(s.health<=0)finish(s,'You succumb to wounds sustained on your journey.');return s;}
export function score(s:Life){return Math.max(0,s.age*5+s.realm*300+s.silver+s.reputation*3);}

export const items:Record<string,{name:string;cost:number;description:string;boost:number}>={jade:{name:'Spirit jade pendant',cost:60,description:'Equip for +20% cultivation speed.',boost:.2},manual:{name:'Breathing manual',cost:100,description:'Equip for +35% cultivation speed.',boost:.35},pill:{name:'Recovery pill',cost:18,description:'Consume to restore 35 health.',boost:0},herb:{name:'Spirit herb',cost:12,description:'Consume to gain 12 qi.',boost:0}};
export function migrate(s:Life,now=Date.now()):Life{return {...s,childAppearance:s.childAppearance??(s.gender==='Female'?5:0),job:s.job??null,people:s.people.map(p=>({...p,details:npcDetails(p)})),appearance:s.appearance??null,school:s.age>=18?{...(s.school??{grades:50,conduct:80}),enrolled:false,graduated:true}:s.school??{enrolled:false,graduated:false,grades:50,conduct:80},inventory:s.inventory??{},equipped:s.equipped??null,master:s.master??null,clan:s.clan??null,favor:s.favor??0,energy:s.energy??3,idle:s.idle??false,lastTick:s.lastTick??now,lastEventAge:s.lastEventAge??-2};}
export function boosts(s:Life){return [{name:s.trait+' personality',value:s.trait==='Disciplined'?.15:s.trait==='Patient'?.1:0},{name:s.master?'Master '+s.master:'No master',value:s.master&&s.people.some(p=>p.name===s.master&&p.alive)?.25:0},{name:s.equipped?items[s.equipped]?.name??'Equipment':'No equipped item',value:s.equipped&&s.inventory[s.equipped]>0?items[s.equipped]?.boost??0:0},{name:s.clan??'No clan',value:s.clan?.1:0}];}
export function multiplier(s:Life){return 1+boosts(s).reduce((a,b)=>a+b.value,0);}
export function rate(s:Life){return (1+s.talent*.5+s.stats.willpower/20)*multiplier(s);}
export function tick(old:Life,now=Date.now()):Life{const elapsed=Math.min(4*3600,Math.max(0,(now-old.lastTick)/1000));if(now<=old.lastTick)return old;const s={...old,lastTick:now};if(s.idle&&!s.dead&&s.age>=12&&!s.event&&s.realm<4)s.qi+=elapsed/60*rate(s);return s;}
export function toggleIdle(s:Life,now=Date.now()){if(s.age<12||s.dead||s.event||s.realm>=4)return s;const next=tick(s,now);return {...next,idle:!next.idle};}
function background(s:Life,r:()=>number){const memories=s.age<3?backgroundEventPool.baby:s.age<12?backgroundEventPool.child:backgroundEventPool.adult;add(s,pick(memories,r));if(s.age===12)add(s,'Your meridians awaken. You can now cultivate, seek a teacher, and explore beyond familiar streets.');if(s.age===18)add(s,'You come of age. The clan halls and royal offices will now hear your petitions.');}
export type Activity='train'|'market'|'alley'|'royal'|'clan'|'master'|'talk'|'gift'|'spar';
export function activity(old:Life,kind:Activity,target=0,r=Math.random):Life{if(old.dead||old.event||old.energy<=0||old.age<(kind==='talk'?5:kind==='royal'||kind==='clan'?18:12))return old;const s=structuredClone(old);const p=s.people[target];if(['talk','gift','spar'].includes(kind)&&(!p?.alive))return old;if(kind==='gift'&&s.silver<10)return old;if(kind==='clan'&&(s.clan||s.reputation<10))return old;if(kind==='master'&&(s.master||s.reputation<5))return old;s.energy--;if(kind==='train'){s.stats.strength++;s.stats.willpower++;s.health-=4;add(s,'You repeat your stances until your limbs tremble. Strength and willpower rise by 1; you lose 4 health.');}if(kind==='market'){s.silver+=8;add(s,'You spend an afternoon helping a stallholder. Eight silver and a few trading lessons are your reward.');}if(kind==='alley'){if(r()<.4){s.health-=15;add(s,'A back-alley deal turns ugly. You escape with bruises and lose 15 health.');}else{s.inventory.herb=(s.inventory.herb??0)+1;add(s,'An alley trader gives you a spirit herb in return for carrying a parcel.');}}if(kind==='royal'){s.favor+=5;s.reputation+=3;const pay=s.favor>=15?20:5;s.silver+=pay;add(s,'You deliver records for the royal office. Favor rises by 5, reputation by 3, and you earn '+pay+' silver.');}if(kind==='clan'){s.clan='Azure Reed Clan';add(s,'The Azure Reed Clan accepts your petition. Shared training grounds grant +10% cultivation speed.');}if(kind==='master'){const teacher=generateNpc('Master',45,2,50,r,200);s.master=teacher.name;s.people.push(teacher);add(s,teacher.name+' accepts you as a student. Her guidance grants +25% cultivation speed while she lives.');}if(kind==='talk'){p.bond=clamp(p.bond+8);add(s,'You listen as '+p.name+' speaks about '+(p.role==='Family'?'your family’s hopes for your future':'their hopes along the martial path')+'. Your bond grows by 8.');}if(kind==='gift'){s.silver-=10;p.bond=clamp(p.bond+15);add(s,'You spend 10 silver on a thoughtful gift for '+p.name+'. Your bond grows by 15.');}if(kind==='spar'){s.stats.strength++;s.qi+=5;p.bond=clamp(p.bond+3);s.health-=5;add(s,'You spar with '+p.name+'. You gain 1 strength, 5 qi and 3 bond, but lose 5 health.');}if(s.health<=0)finish(s,'Your wounds prove too severe.');return s;}
export function purchase(old:Life,id:string):Life{const item=items[id];if(!item||old.age<12||old.dead||old.event||old.silver<item.cost)return old;const s=structuredClone(old);s.silver-=item.cost;s.inventory[id]=(s.inventory[id]??0)+1;add(s,'You buy '+item.name+' for '+item.cost+' silver.');return s;}
export function useItem(old:Life,id:string):Life{if(!items[id]||!(old.inventory[id]>0)||old.dead||old.event)return old;const s=structuredClone(old);if(items[id].boost){s.equipped=s.equipped===id?null:id;add(s,s.equipped?'You equip '+items[id].name+'.':'You put away '+items[id].name+'.');}else{s.inventory[id]--;if(id==='pill')s.health=clamp(s.health+35);else s.qi+=12;add(s,'You use '+items[id].name+'. '+(id==='pill'?'Your injuries begin to mend.':'Warm spiritual energy enters your meridians.'));}return s;}

export const families=[{name:'Farming household',silver:12,story:'a hardworking farming family'},{name:'Merchant household',silver:45,story:'a comfortable merchant family'},{name:'Declining martial clan',silver:12,story:'a once-respected martial family whose fortune has faded'},{name:'Poor laborer family',silver:5,story:'a poor family surviving on seasonal labor'},{name:'Herbalist household',silver:25,story:'a family of village herbalists'},{name:'Blacksmith household',silver:30,story:'a family of hardworking blacksmiths'},{name:'Scholar household',silver:20,story:'a modest family of scholars'},{name:'Minor noble family',silver:80,story:'a wealthy minor noble family'}];
export function origin(s:Life){const mom=s.people.find(p=>p.role==='Mother')?.name??s.people.find(p=>p.role==='Family')?.name??'an unnamed mother';const dad=s.people.find(p=>p.role==='Father')?.name??'an unnamed father';return s.name+' is born into '+(families.find(f=>f.name===s.family)?.story??s.family.toLowerCase())+' in '+s.village+'. Their mother is '+mom+' and their father is '+dad+'. The household greets this new life with hope.';}
export function startLife(s:Life,r=Math.random):Life{const n=structuredClone(s);if(!n.people.some(p=>p.role==='Father'))n.people.push({name:pick(['Lin Bo','Wen Hao','Shen Jun','Xiao Feng'],r),role:'Father',bond:75,age:26+Math.floor(r()*14),realm:0,alive:true});if(!n.people.every(p=>p.details?.job)){n.people=n.people.map((p,i)=>generateNpc(p.role,p.age,p.realm,p.bond,r,i));for(let i=0;i<5;i++)n.people.push(generateNpc('Villager',20+Math.floor(r()*35),0,20,r,i+10));}n.log=[{age:0,text:origin(n)}];return n;}
function schoolYear(s:Life,r=Math.random){if(s.age>=6&&s.age<18&&!s.school.enrolled){s.school.enrolled=true;const teacher=generateNpc('Teacher',35,1,50,r,100);const classmates=Array.from({length:4},(_,i)=>generateNpc('Classmate',s.age-1,0,35+Math.floor(r()*15),r,101+i));s.people.push(teacher,...classmates);s.memories.schoolWelcome=1;add(s,'You enroll at the '+s.village+' school. '+teacher.name+' welcomes you, and '+classmates.map(p=>p.name).join(', ')+' share your classroom.');}if(s.school.enrolled&&s.age<18){s.school.grades=clamp(s.school.grades-2);const gain=Math.round((8+s.talent*3+s.school.grades/10)*multiplier(s));s.qi+=gain;add(s,'Daily breathing exercises and martial lessons grant '+gain+' qi this school year.');if(s.realm<2&&s.qi>=threshold(s)){s.qi-=threshold(s);s.realm++;add(s,'Under your teacher’s supervision, you break through to '+realms[s.realm]+'. School can guide you as far as Foundation Establishment.');}add(s,'Another school year begins. Your studies stand at '+s.school.grades+'/100; assignments and practice can improve them.');}if(s.age>=18&&s.school.enrolled){s.school.enrolled=false;s.school.graduated=true;add(s,'You complete village school with '+s.school.grades+'/100 in your studies and '+s.school.conduct+'/100 conduct. '+(s.school.grades>=80?'Your teachers commend your dedication.':'Your school years leave lessons and friendships to carry forward.'));}}
export type SchoolAction='assignments'|'practice'|'talk'|'befriend'|'train'|'fight'|'guidance';
export function schoolAction(old:Life,action:SchoolAction,target=0,r=Math.random):Life{if(!old.school.enrolled||old.age<6||old.age>=18||old.dead||old.event||old.energy<1)return old;const s=structuredClone(old);const p=s.people[target];if(['talk','befriend','train','fight','guidance'].includes(action)&&(!p?.alive||!['Teacher','Classmate','Childhood friend'].includes(p.role)))return old;if(action==='guidance'&&p.role!=='Teacher')return old;if(['train','fight','befriend'].includes(action)&&p.role==='Teacher')return old;s.energy--;if(action==='assignments'){s.school.grades=clamp(s.school.grades+10);s.stats.intelligence++;add(s,'You stay after class to finish a difficult assignment. Your grades rise by 10 and intelligence by 1.');}if(action==='practice'){s.stats.strength++;s.stats.willpower++;add(s,'You practice the basic school forms. Strength and willpower rise by 1.');}if(action==='guidance'){s.school.grades=clamp(s.school.grades+6);p.bond=clamp(p.bond+5);add(s,p.name+' patiently explains a lesson. Grades rise by 6; your bond grows by 5.');}if(action==='talk'||action==='befriend'){p.bond=clamp(p.bond+(action==='talk'?8:12));add(s,'You '+(action==='talk'?'share stories with ':'invite to lunch ')+p.name+'. '+(p.bond>=60?'A friendship begins to blossom.':'You get to know each other a little better.'));}if(action==='train'){s.stats.strength++;s.qi+=3;p.bond=clamp(p.bond+6);add(s,'You practice with '+p.name+'. You gain 1 strength, 3 qi and 6 bond.');}if(action==='fight'){const win=r()<Math.min(.85,.35+s.stats.strength/100);s.health-=win?8:18;p.bond=clamp(p.bond-25);s.school.conduct=clamp(s.school.conduct-20);s.school.grades=clamp(s.school.grades-5);add(s,'You start a fight with '+p.name+'. '+(win?'You win, but leave with bruises.':'You lose and leave badly bruised.')+' Your conduct falls by 20, grades by 5, and bond by 25.');}if(s.health<=0)finish(s,'You succumb to injuries from a school fight.');return s;}
export function selectAppearance(old:Life,id:number):Life{if(old.age<18||old.dead||old.appearance!==null||!Number.isInteger(id)||id<0||id>9)return old;const s={...old,appearance:id,log:[...old.log]};add(s,'At adulthood, you choose the face that will accompany the next chapter of your life.');return s;}

export function isParent(p:Person){return ['Mother','Father','Family'].includes(p.role);}
export function npcDetails(p:Person):NpcDetails{if(p.details)return {...p.details,gender:p.details.portrait<5?'Male':'Female'};let h=0;for(const ch of p.name)h=(h*31+ch.charCodeAt(0))>>>0;const feminine=p.role==='Mother'||['Lan Ning','Elder Mei'].includes(p.name);return {id:'npc-'+h,portrait:feminine?5+h%5:h%5,friend:!isParent(p)&&p.bond>=60,trait:['Patient','Ambitious','Kind','Disciplined','Proud'][h%5],goal:p.role==='Teacher'?'Guide the next generation':isParent(p)?'Keep the family safe':'Establish a name in the martial world',root:['Fire','Water','Wood','Earth','Metal'][h%5],talent:1+h%3,qi:0,wealth:10+h%40,health:p.alive?100:0,stats:{strength:6+h%15,intelligence:7+(h>>>3)%14,willpower:8+(h>>>5)%13},memories:[]};}
export function inRelationships(p:Person){return isParent(p)||npcDetails(p).friend;}
function npcYear(p:Person,s:Life){const d=p.details!;if(p.age>=6){d.qi+=5+d.talent*4;d.stats.willpower=Math.min(100,d.stats.willpower+1);if(p.realm<4&&d.qi>=40+p.realm*50){d.qi-=40+p.realm*50;p.realm++;const text=p.name+' reaches '+realms[p.realm]+' through steady practice.';d.memories.unshift(text);add(s,text);}}if(p.age>=18)d.wealth+=3+d.talent;if(p.age===18){d.memories.unshift('I came of age and began my adult life.');add(s,p.name+' comes of age. Their youthful features settle into a familiar adult face.');}d.memories=d.memories.slice(0,30);}
export type Interaction='talk'|'gift'|'spar'|'befriend'|'guidance'|'train'|'fight';
export function interact(old:Life,id:string,kind:Interaction,r=Math.random):Life{const i=old.people.findIndex(p=>npcDetails(p).id===id);if(i<0||!old.people[i].alive||old.dead||old.event||old.energy<1)return old;const p=old.people[i];let next:Life;if(kind==='befriend'){if(old.age<5||isParent(p))return old;next=structuredClone(old);next.energy--;const target=next.people[i];target.details=npcDetails(target);target.bond=clamp(target.bond+12);if(target.bond>=60){target.details.friend=true;add(next,'You and '+target.name+' become friends. They now appear in Relationships.');}else add(next,target.name+' enjoys your company but needs more time. Bond rises by 12; friendship forms at 60.');}else if(['guidance','train','fight'].includes(kind)||(kind==='talk'&&old.school.enrolled&&['Teacher','Classmate','Childhood friend'].includes(p.role))){next=schoolAction(old,kind as SchoolAction,i,r);}else next=activity(old,kind as Activity,i,r);if(next===old)return old;const target=next.people[i];target.details=npcDetails(target);target.details.memories.unshift('Age '+next.age+': '+next.log[0].text);target.details.memories=target.details.memories.slice(0,30);if(kind==='fight'&&target.bond<30)target.details.friend=false;return next;}

export function generateNpc(role:string,age:number,realm:number,bond:number,r=Math.random,slot=0):Person{const template=role==='Teacher'||role==='Master'?npcPool.find(t=>t.key==='teacher')!:role==='Classmate'||role==='Childhood friend'?npcPool.find(t=>t.key==='student')!:draw(npcPool.filter(t=>!['teacher','student'].includes(t.key)),r);const female=role==='Mother'||role!=='Father'&&r()<.5;const p:Person={name:randomName(r),role,age,realm,bond,alive:true};const d=npcDetails(p);d.id+='-'+slot+'-'+Math.floor(r()*1e9);d.portrait=(female?5:0)+Math.floor(r()*5);d.gender=female?'Female':'Male';d.portraitSet=Math.floor(r()*2);d.job=template.job;d.background=draw(backgroundPool,r);d.specialTrait=draw(traitPool,r);d.trait=draw(personalityPool,r);d.goal=template.goal;d.root=draw(['Fire','Water','Wood','Earth','Metal'],r);d.talent=1+Math.floor(r()*3);d.wealth=5+Math.floor(r()*75);d.stats={strength:template.strength+Math.floor(r()*5),intelligence:template.intelligence+Math.floor(r()*5),willpower:template.willpower+Math.floor(r()*5)};d.friend=false;p.details=d;return p;}
export function eventFor(s:Life,r=Math.random):Event{const e=baseEventFor(s,r);const friend=s.people.find(p=>p.role==='Childhood friend')?.name??'your former classmate';return {...e,text:e.text.replaceAll('Chen Tao',friend),choices:e.choices.map(c=>({...c,label:c.label.replaceAll('Chen Tao',friend)}))};}
export function acknowledgeSchool(s:Life):Life{if(s.memories.schoolWelcome!==1)return s;return {...s,memories:{...s.memories,schoolWelcome:2}};}

export const jobs=[{id:'laborer',title:'Village laborer',salary:25,grades:0,strength:0,intelligence:0,realm:0,description:'Steady practical work. No academic requirements.'},{id:'trader',title:'Merchant assistant',salary:50,grades:30,strength:0,intelligence:10,realm:0,description:'Learn accounts and negotiate with suppliers.'},{id:'guard',title:'Caravan guard',salary:75,grades:0,strength:15,intelligence:0,realm:1,description:'Protect travelers along the mountain roads.'},{id:'healer',title:'Herbalist apprentice',salary:65,grades:60,strength:0,intelligence:15,realm:0,description:'Prepare remedies and study medicinal plants.'},{id:'instructor',title:'Martial instructor',salary:110,grades:70,strength:15,intelligence:12,realm:2,description:'Teach the next generation of cultivators.'},{id:'clerk',title:'Imperial clerk',salary:90,grades:80,strength:0,intelligence:18,realm:0,description:'Serve in the provincial administration.'}];
export function jobRequirements(s:Life,j:typeof jobs[number]){const reasons:string[]=[];if(s.age<18)reasons.push('Age 18');if(!s.school.graduated)reasons.push('School graduation');if(s.school.grades<j.grades)reasons.push('Grades '+j.grades);if(s.stats.strength<j.strength)reasons.push('Strength '+j.strength);if(s.stats.intelligence<j.intelligence)reasons.push('Intelligence '+j.intelligence);if(s.realm<j.realm)reasons.push(realms[j.realm]);return reasons;}
export function applyJob(old:Life,id:string):Life{const j=jobs.find(x=>x.id===id);if(!j||old.dead||old.event||old.job===id||jobRequirements(old,j).length)return old;const s={...old,job:id,memories:{...old.memories,careerYears:0,careerRank:0,careerPerformance:50},log:[...old.log]};add(s,'You are hired as '+j.title+'. Your yearly salary is '+j.salary+' silver, paid when you age up.');return s;}
export function resign(old:Life):Life{if(!old.job||old.dead||old.event)return old;const s={...old,job:null,log:[...old.log]};add(s,'You leave your job to pursue another path.');return s;}


export function career(s:Life){return {years:s.memories.careerYears??0,rank:s.memories.careerRank??0,performance:s.memories.careerPerformance??50,earnings:s.memories.careerEarnings??0};}
export function salary(s:Life){const j=jobs.find(j=>j.id===s.job);return j?Math.round(j.salary*(1+career(s).rank*.35)):0;}
export function careerYear(s:Life){const j=jobs.find(j=>j.id===s.job);if(!j)return;const c=career(s),pay=salary(s);s.silver+=pay;s.memories.careerYears=c.years+1;s.memories.careerEarnings=c.earnings+pay;s.memories.careerPerformance=clamp(c.performance+5);add(s,'You earn '+pay+' silver for a year working as '+j.title+'.');if(c.rank<2&&c.years+1>=2*(c.rank+1)&&s.memories.careerPerformance>=70+c.rank*10){s.memories.careerRank=c.rank+1;s.reputation+=3;add(s,'Promotion! You become a '+(c.rank===0?'senior':'lead')+' '+j.title.toLowerCase()+'. Your salary rises to '+salary(s)+' silver from next year.');}}
export function careerAction(old:Life,action:'effort'|'study'|'leave'):Life{if(!old.job||old.age<18||!old.school.graduated||old.dead||old.event||old.energy<1)return old;const c=career(old);if(action==='effort'&&(old.health<=4||c.performance>=100)||action==='study'&&old.silver<10)return old;const s=structuredClone(old);s.energy--;if(action==='effort'){s.health-=4;s.memories.careerPerformance=clamp(c.performance+15);add(s,'You take extra care with your duties. Work performance rises by 15; you spend 1 activity point and 4 health.');}if(action==='study'){s.silver-=10;s.stats.intelligence++;s.stats.willpower++;s.memories.careerPerformance=clamp(c.performance+8);add(s,'You spend 10 silver on professional training. Intelligence and willpower rise by 1; work performance rises by 8.');}if(action==='leave'){s.health=clamp(s.health+12);s.memories.careerPerformance=clamp(c.performance-5);add(s,'You take a short recovery break. Health rises by 12; work performance falls by 5.');}return s;}
