import{test}from'node:test';import assert from'node:assert/strict';import{birth,act,choose,eventFor,threshold}from'./game.ts';
test('complete life reaches death and cannot continue',()=>{let s=birth(()=>.5);for(let i=0;i<200&&!s.dead;i++){s=act(s,'age',()=>.5);if(s.event)s=choose(s,s.event.choices.length-1,()=>.5);}assert.ok(s.dead);assert.ok(s.age>0);assert.equal(act(s,'age'),s);assert.equal(choose(s,0),s);});
test('pending choice blocks time and unaffordable purchases',()=>{let s=act(birth(),'age',()=>0);assert.equal(act(s,'age'),s);s.silver=0;s.event={id:'test',title:'Shop',text:'',choices:[{label:'Buy',hint:'',effect:{silver:-10}}]};assert.equal(choose(s,0),s);});
test('breakthrough consumes qi and health influences risk',()=>{let s=birth();s.age=14;s.qi=threshold(s);const win=act(s,'breakthrough',()=>0);assert.equal(win.realm,1);assert.equal(win.qi,0);const lose=act(s,'breakthrough',()=>.99);assert.equal(lose.realm,0);assert.equal(lose.health,78);});
test('past kindness returns after five years',()=>{const s=birth();s.age=20;s.memories.saved=15;assert.equal(eventFor(s).id,'repaid');});
test('new lives reset and actions preserve prior states',()=>{const s=birth(()=>.5);const before=JSON.stringify(s);act(s,'age');assert.equal(JSON.stringify(s),before);assert.equal(birth().age,0);});

import{tick,rate,activity,purchase,useItem,multiplier,migrate}from'./game.ts';
test('quiet years create memories without a popup',()=>{const s=act(birth(),'age',()=>.9);assert.equal(s.event,null);assert.ok(s.log.length>1);});
test('random events have a quiet year between them',()=>{let s=act(birth(),'age',()=>0);assert.ok(s.event);s=choose(s,0);s=act(s,'age',()=>0);assert.equal(s.event,null);});
test('offline cultivation is capped and never duplicates elapsed time',()=>{let s=birth();s.age=12;s.idle=true;s.lastTick=1000;const n=tick(s,1000+8*3600000);assert.ok(Math.abs(n.qi-rate(s)*240)<.0001);assert.equal(tick(n,n.lastTick),n);s.dead=true;assert.equal(tick(s,61000).qi,0);s.dead=false;s.age=2;assert.equal(tick(s,61000).qi,0);});
test('purchases, equipment and consumables respect ownership',()=>{let s=birth();s.age=12;s.silver=100;s=purchase(s,'jade');assert.equal(s.silver,40);assert.equal(s.inventory.jade,1);const before=multiplier(s);s=useItem(s,'jade');assert.ok(Math.abs(multiplier(s)-before-.2)<.001);assert.equal(purchase(s,'manual'),s);assert.equal(useItem(s,'pill'),s);s=purchase(s,'pill');s.health=40;s=useItem(s,'pill');assert.equal(s.health,75);assert.equal(s.inventory.pill,0);});
test('social actions cost points and target one person',()=>{let s=birth();s.age=12;const old=s.people[0].bond;s=activity(s,'talk',1);assert.equal(s.energy,2);assert.equal(s.people[0].bond,old);assert.equal(s.people[1].bond,58);s.energy=0;assert.equal(activity(s,'train'),s);});
test('masters require reputation and add a living teacher bonus',()=>{let s=birth();s.age=18;assert.equal(activity(s,'master'),s);s.reputation=10;s=activity(s,'master');assert.ok(s.master);const withTeacher=multiplier(s);s.people.find(p=>p.name===s.master)!.alive=false;assert.ok(Math.abs(withTeacher-multiplier(s)-.25)<.001);});
test('old saves receive mechanics defaults',()=>{const s=birth();delete (s as any).inventory;delete (s as any).lastTick;assert.deepEqual(migrate(s,123).inventory,{});assert.equal(migrate(s,123).lastTick,123);});

import{schoolAction,selectAppearance,families}from'./game.ts';
test('birth chronicle has village, background and named parents',()=>{const s=birth();assert.ok(s.log[0].text.includes(s.village));for(const role of ['Mother','Father'])assert.ok(s.log[0].text.includes(s.people.find(p=>p.role===role)!.name));assert.ok(families.some(f=>f.name===s.family&&f.silver===s.silver));});
test('school enrolls at six with peers and graduates at eighteen',()=>{let s=birth();s.age=5;s=act(s,'age',()=>.9);assert.ok(s.school.enrolled);assert.equal(s.people.find(p=>p.role==='Classmate')!.age,6);s.age=17;s=act(s,'age',()=>.9);assert.equal(s.school.enrolled,false);assert.ok(s.school.graduated);});
test('assignments consume energy and school fights have consequences',()=>{let s=birth();s.age=5;s=act(s,'age',()=>.9);const grades=s.school.grades;s=schoolAction(s,'assignments');assert.equal(s.school.grades,grades+10);assert.equal(s.energy,2);const i=s.people.findIndex(p=>p.role==='Classmate');s=schoolAction(s,'fight',i,()=>.99);assert.equal(s.health,82);assert.equal(s.school.conduct,60);s.energy=0;assert.equal(schoolAction(s,'practice'),s);});
test('appearance is age gated, valid, and chosen once',()=>{let s=birth();assert.equal(selectAppearance(s,2),s);s.age=18;assert.equal(selectAppearance(s,10),s);s=selectAppearance(s,9);assert.equal(s.appearance,9);assert.equal(selectAppearance(s,0),s);assert.equal(migrate(s).appearance,9);});

import{npcDetails,inRelationships,interact}from'./game.ts';
test('new relationships list includes only parents',()=>{const s=birth();assert.equal(s.people.filter(inRelationships).length,2);assert.ok(s.people.filter(inRelationships).every(p=>['Mother','Father'].includes(p.role)));});
test('befriending adds the target and records history without mutating old save',()=>{const s=birth();s.age=6;const p=s.people.find(p=>p.role==='Childhood friend')!;const id=npcDetails(p).id;const n=interact(s,id,'befriend');assert.ok(inRelationships(n.people.find(p=>npcDetails(p).id===id)!));assert.equal(inRelationships(p),false);assert.equal(n.energy,2);assert.ok(npcDetails(n.people[1]).memories.length);assert.equal(npcDetails(migrate(n).people[1]).id,id);});
test('martial school gains qi and performs supervised breakthroughs',()=>{let s=birth();s.age=5;s=act(s,'age',()=>.9);assert.ok(s.qi>0);s.qi=threshold(s);s=act(s,'age',()=>.9);assert.equal(s.realm,1);assert.ok(s.log.some(e=>e.text.includes('teacher’s supervision')));});
test('NPC identities and portrait indices persist as they age',()=>{let s=birth();const id=npcDetails(s.people[1]).id;const portrait=npcDetails(s.people[1]).portrait;s=act(s,'age',()=>.9);assert.equal(npcDetails(s.people[1]).id,id);assert.equal(npcDetails(s.people[1]).portrait,portrait);assert.equal(interact(s,id,'befriend'),s);});

import{generateNpc,acknowledgeSchool}from'./game.ts';
test('NPC pool assignments persist and vary between rolls',()=>{const a=generateNpc('Villager',25,0,20,()=>.1,1);const b=generateNpc('Villager',25,0,20,()=>.8,2);assert.notEqual(a.name,b.name);assert.notEqual(npcDetails(a).portraitSet,npcDetails(b).portraitSet);assert.ok(npcDetails(a).job);assert.ok(npcDetails(a).background);assert.deepEqual(npcDetails(migrate({...birth(),people:[a]}).people[0]),npcDetails(a));});
test('school welcome is acknowledged once and stays acknowledged',()=>{let s=birth();s.age=5;s=act(s,'age',()=>.9);assert.equal(s.memories.schoolWelcome,1);s=acknowledgeSchool(s);assert.equal(s.memories.schoolWelcome,2);s.event=null;s=act(s,'age',()=>.9);assert.equal(s.memories.schoolWelcome,2);});

import{applyJob,jobs,resign}from'./game.ts';
test('jobs require credentials and pay once per aged year',()=>{let s=birth();assert.equal(applyJob(s,'laborer'),s);s.age=18;s.school.graduated=true;s=applyJob(s,'laborer');const cash=s.silver;assert.equal(s.job,'laborer');s=act(s,'age',()=>.9);assert.equal(s.silver,cash+25);s.event=null;s=resign(s);const after=s.silver;s=act(s,'age',()=>.9);assert.equal(s.silver,after);});
test('unqualified applications do not replace a job or grant money',()=>{let s=birth();s.age=18;s.school.graduated=true;s.school.grades=0;s=applyJob(s,'laborer');assert.equal(applyJob(s,'instructor'),s);assert.equal(applyJob(s,'unknown'),s);});
test('NPC gender always follows assigned portrait row',()=>{for(const value of [.1,.8]){const p=generateNpc('Villager',25,0,20,()=>value);const d=npcDetails(p);assert.equal(d.gender,d.portrait<5?'Male':'Female');}const s=birth();assert.equal(npcDetails(s.people.find(p=>p.role==='Mother')!).gender,'Female');assert.equal(npcDetails(s.people.find(p=>p.role==='Father')!).gender,'Male');});

import{career,careerAction,salary}from'./game.ts';
test('career review promotes after tenure and pays old salary before raise',()=>{let s=birth();s.age=18;s.school.graduated=true;s=applyJob(s,'laborer');const original=JSON.stringify(s);const n=careerAction(s,'effort');assert.equal(JSON.stringify(s),original);assert.equal(n.energy,2);assert.equal(career(n).performance,65);s=act(n,'age',()=>.9);assert.equal(career(s).rank,0);const money=s.silver;s=act(s,'age',()=>.9);assert.equal(s.silver,money+25);assert.equal(career(s).rank,1);assert.equal(salary(s),34);const after=s.silver;s=act(s,'age',()=>.9);assert.equal(s.silver,after+34);});
test('career costs, health safety and job switching preserve earned money',()=>{let s=birth();s.age=18;s.school.graduated=true;s=applyJob(s,'laborer');s.silver=9;assert.equal(careerAction(s,'study'),s);s.health=4;assert.equal(careerAction(s,'effort'),s);s.energy=0;assert.equal(careerAction(s,'leave'),s);s.memories.careerRank=2;s.memories.careerYears=8;s.memories.careerEarnings=250;s.school.grades=100;s.stats.intelligence=30;const n=applyJob(s,'clerk');assert.equal(career(n).rank,0);assert.equal(career(n).years,0);assert.equal(career(n).earnings,250);assert.equal(n.silver,9);assert.equal(career(s).rank,2);});
test('legacy employed saves receive career defaults',()=>{let s=birth();s.job='laborer';s=migrate(s);assert.deepEqual(career(s),{years:0,rank:0,performance:50,earnings:0});assert.equal(salary(s),25);});
