import{GameIcon}from'./Art';
import{NpcList}from'./NPC';
import{useState}from'react';import{Face}from'./School';
import{activity,purchase,useItem,items,boosts,multiplier,rate,toggleIdle,threshold,realms,type Life,type Activity}from'./game';
type Props={s:Life;set:(f:(s:Life)=>Life)=>void};
export function Portrait({s}:{s:Life}){const stage=s.age<3?['👶','Baby']:s.age<12?['🧒','Child']:s.age<18?['🧑','Teen']:['👤','Adult'];return <div className={'portrait '+(s.idle&&!s.event?'cultivating':'')}>{s.age>=18&&s.appearance!==null?<Face id={s.appearance}/>:s.age>=3?<Face id={s.childAppearance} child/>:<span aria-hidden="true">{stage[0]}</span>}<b>{stage[1]}</b><small>{s.age>=18?'Your chosen appearance':'Age '+s.age}</small></div>}
export function Cultivation({s,set}:Props){return <section className="card"><div className="eyebrow">BODY, BREATH & SPIRIT</div><h2 className="art-heading"><GameIcon name="Cultivation"/>{realms[s.realm]}</h2><Portrait s={s}/><p>{s.root} root · {s.trait} · {s.master?'Student of '+s.master:'Self-taught'}</p><label>Qi: {s.qi.toFixed(1)} / {threshold(s)}<progress max={threshold(s)} value={Math.min(s.qi,threshold(s))}/></label><p>{rate(s).toFixed(2)} qi / real minute · +{Math.round((multiplier(s)-1)*100)}% total speed</p><button className="primary" disabled={s.age<12||s.dead||!!s.event||s.realm>=4} onClick={()=>set(x=>toggleIdle(x))}>{s.idle?'Pause idle cultivation':'Start idle cultivation'}</button><p>{s.age<12?'Unlocks at age 12.':s.event?'Paused during your current event.':s.idle?'Cultivation is active. Your age does not advance.':'Cultivation is paused.'} Offline gain is capped at 4 hours per absence. Breakthroughs are manual.</p><h3>Speed bonuses</h3>{boosts(s).map(b=><div className="bonus" key={b.name}><span>{b.name}</span><b>+{Math.round(b.value*100)}%</b></div>)}<p>Bonuses add together and apply to idle cultivation and year-long cultivation. Equip one item at a time.</p><div className="attributes">{realms.map((realm,i)=><div key={realm}><span>{realm}</span><b>{i===s.realm?'Current':i<s.realm?'Reached':'Ahead'}</b></div>)}</div></section>}
export function Activities({s,set}:Props){const[section,open]=useState<string|null>(null);const groups:Record<string,string[]>={'People':[],'Training':['train','master'],'Market':['market'],'Alleys':['alley'],'Royal office':['royal'],'Clans':['clan']};const entries:[Activity,string,string,number][]=[['train','Training grounds','+1 strength, +1 willpower · −4 health',12],['market','Market work','Help a stallholder · +8 silver',12],['alley','Explore the alleys','60% spirit herb · 40% lose 15 health',12],['master','Seek a master','Requires 5 reputation · +25% cultivation speed',12],['royal','Royal office','+5 favor, +3 reputation · 5 silver, or 20 at 15+ favor',18],['clan','Petition the Azure Reed Clan','Requires 10 reputation · +10% cultivation speed',18]];return <section className="card"><h2>Beyond your doorstep</h2><p>{s.energy} / 3 activity points remain. Each outing costs 1 point; aging restores all three.</p>{section===null?<div className="activity-categories">{Object.keys(groups).map(name=><button className="outline" key={name} onClick={()=>open(name)}><GameIcon name={name==="People"?"Relationships":name==="Training"?"Activities":name==="Market"?"Inventory":name==="Royal office"?"Occupation":name==="Clans"?"School":"Fate"}/><span>{name}</span><span aria-hidden="true">→</span></button>)}</div>:<><button className="outline" onClick={()=>open(null)}>← All activities</button><h3>{section}</h3>{section==='People'&&<NpcList s={s} set={set} mode="all"/>}<div className="choices">{entries.filter(e=>groups[section].includes(e[0])).map(([id,name,hint,age])=><button key={id} disabled={s.dead||!!s.event||s.energy<1||s.age<age||id==='master'&&(!!s.master||s.reputation<5)||id==='clan'&&(!!s.clan||s.reputation<10)} onClick={()=>set(x=>activity(x,id))}><span><b>{name}</b><small>{hint} · Age {age}+</small></span></button>)}</div>{section==='Market'&&<><h3>Market stalls</h3>{Object.entries(items).map(([id,item])=><div className="shop-row" key={id}><div><b>{item.name}</b><p>{item.description}</p></div><button className="outline" disabled={s.age<12||s.silver<item.cost||s.dead||!!s.event} onClick={()=>set(x=>purchase(x,id))}>Buy · {item.cost} silver</button></div>)}</>}</>}</section>}
export function Inventory({s,set}:Props){return <section className="card"><h2 className="art-heading"><GameIcon name="Inventory"/>Inventory & assets</h2><p>Silver: {s.silver} · Royal favor: {s.favor}</p><p>Clan: {s.clan??'Unaffiliated'} · Residence: family home in {s.village}</p><p>The family home is your residence, not a saleable property.</p>{Object.entries(s.inventory).filter(([,n])=>n>0).length===0&&<p>Your bag is empty. Visit the market or explore the alleys.</p>}{Object.entries(s.inventory).filter(([id,n])=>n>0&&items[id]).map(([id,n])=><div className="shop-row" key={id}><div><b>{items[id].name} × {n}</b><p>{items[id].description}</p></div><button className="outline" disabled={s.dead||!!s.event} onClick={()=>set(x=>useItem(x,id))}>{items[id].boost?s.equipped===id?'Unequip':'Equip':'Use'}</button></div>)}</section>}
export function People({s,set}:Props){return <section className="card"><h2 className="art-heading"><GameIcon name="Relationships"/>Relationships</h2><p>Your parents and established friends. Select a name to view their profile.</p><NpcList s={s} set={set}/></section>}

