import{useState}from'react';
import{jobs,jobRequirements,applyJob,resign,realms,career,salary,careerAction,type Life}from'./game';
import{GameIcon}from'./Art';
export function Occupation({s,set}:{s:Life;set:(f:(s:Life)=>Life)=>void}){
 const [filter,setFilter]=useState('all'),[confirm,setConfirm]=useState(false);const current=jobs.find(j=>j.id===s.job),c=career(s);const blocked=s.dead||!!s.event||s.energy<1;const available=jobs.filter(j=>!jobRequirements(s,j).length);const listings=filter==='eligible'?available:jobs;
 return <section className="career-page"><div className="career-title"><div><div className="eyebrow">AMBITION HAS A DAILY PRACTICE</div><h1>Your working life</h1><p>Build a reputation. Master your craft. Earn your place.</p></div><GameIcon name="Occupation"/></div>
 <section className="card career-current"><div className="eyebrow">{current?'YOUR CURRENT POSITION':'A NEW CHAPTER'}</div><h2>{current?['','Senior ','Lead '][c.rank]+current.title:'Find your calling'}</h2><p>{current?current.description:'Your education and cultivation open different doors. Choose a role below to begin.'}</p><div className="career-metrics"><div><small>ANNUAL SALARY</small><strong>{salary(s)} <em>silver</em></strong></div><div><small>YEARS IN THIS JOB</small><strong>{current?c.years:0}</strong></div><div><small>CAREER EARNINGS</small><strong>{c.earnings} <em>silver</em></strong></div></div>
 {current&&<><label className="performance-label">Work performance <b>{c.performance}/100</b></label><progress aria-label="Work performance" value={c.performance} max={100}/><p>{c.rank===2?'You have reached the highest rank in this career.':`Next promotion: ${2*(c.rank+1)} years in this job and ${70+c.rank*10} performance. +35% of base salary per rank. Annual reviews add 5 performance.`}</p><div className="career-actions"><button disabled={blocked||s.health<=4||c.performance>=100} onClick={()=>set(x=>careerAction(x,'effort'))}><b>Go the extra mile</b><small>+15 performance · −4 health</small></button><button disabled={blocked||s.silver<10} onClick={()=>set(x=>careerAction(x,'study'))}><b>Professional training</b><small>−10 silver · +1 intelligence & willpower · +8 performance</small></button><button disabled={blocked} onClick={()=>set(x=>careerAction(x,'leave'))}><b>Take a recovery break</b><small>+12 health · −5 performance</small></button></div><p className="career-note">Each action costs 1 activity point. {s.energy}/3 remain. Salary is paid when a year passes; promotions affect the following year's pay.</p>{confirm?<div className="resign-confirm"><p>Leave this role? Tenure and rank start over when you take another job.</p><button className="outline" disabled={s.dead||!!s.event} onClick={()=>{set(x=>resign(x));setConfirm(false);}}>Confirm resignation</button><button className="outline" onClick={()=>setConfirm(false)}>Keep my job</button></div>:<button className="career-resign" onClick={()=>setConfirm(true)}>Resign from this position</button>}</>}
 </section><section className="card credentials"><h3>Your credentials</h3><span>Grades <b>{s.school.grades}/100</b></span><span>Strength <b>{s.stats.strength}</b></span><span>Intelligence <b>{s.stats.intelligence}</b></span><span>Realm <b>{realms[s.realm]}</b></span></section>
 <div className="career-list-heading"><h2>Opportunities</h2><div className="career-filters"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All roles ({jobs.length})</button><button aria-pressed={filter==='eligible'} onClick={()=>setFilter('eligible')}>Qualified ({available.length})</button></div></div><div className="job-grid">{listings.map(j=>{const missing=jobRequirements(s,j);return <article className="card job-card" key={j.id}><span className={'job-status '+(!missing.length?'eligible':'')}>{s.job===j.id?'Employed here':missing.length?'Requirements to meet':'Qualified'}</span><h3>{j.title}</h3><p>{j.description}</p><div className="job-pay">{j.salary} <small>silver / year · starting pay</small></div><p className="job-requirements">{missing.length?'Needs: '+missing.join(' · '):'You meet every requirement.'}</p><button className="outline" disabled={!!missing.length||s.dead||!!s.event||s.job===j.id} onClick={()=>{set(x=>applyJob(x,j.id));setConfirm(false);}}>{s.job===j.id?'Your current role':current?'Switch to this career':'Apply for this role'}</button></article>})}</div>{!listings.length&&<p>No matching roles yet. Improve your credentials to open more opportunities.</p>}<p className="career-note">Changing careers resets rank and tenure. Applying never grants an immediate payment.</p></section>;
}
