import type{Event}from'./game';
export const namePool={surnames:['Lin','Shen','Wen','Liu','Xiao','Yun','Su','Zhao','Bai','Lu','Gu','Han'],given:['Wei','Lan','Ming','Yue','Bo','Rong','Ning','Jun','An','Feng','Qing','Hao','Xiu','Lei','Yan','Jin','Tao','Mei','Ru','Yi']};
export const personalityPool=['Patient','Ambitious','Kind','Disciplined','Proud','Reserved','Cheerful','Curious'];
export const traitPool=['Keen memory','Strong physique','Steady hands','Quick learner','Observant','Silver tongue'];
export const backgroundPool=['Raised by traveling merchants','Born in a farming hamlet','Descended from a declining clan','Raised near a mountain shrine','Apprenticed in a family workshop','Educated by a village scholar','Grew up along the caravan roads','Raised in a household of healers'];
export const npcPool=[{key:'farmer',job:'Farmer',goal:'Secure a good harvest',strength:12,intelligence:7,willpower:12},{key:'merchant',job:'Merchant',goal:'Open a shop in the provincial capital',strength:7,intelligence:14,willpower:10},{key:'healer',job:'Herbalist',goal:'Discover a cure for spirit fever',strength:6,intelligence:16,willpower:13},{key:'smith',job:'Blacksmith',goal:'Forge a blade worthy of a master',strength:17,intelligence:9,willpower:14},{key:'guard',job:'Caravan guard',goal:'Keep the mountain roads safe',strength:16,intelligence:8,willpower:13},{key:'scholar',job:'Scholar',goal:'Recover a forgotten manuscript',strength:6,intelligence:18,willpower:12},{key:'teacher',job:'Martial instructor',goal:'Guide the next generation',strength:14,intelligence:17,willpower:18},{key:'student',job:'Martial student',goal:'Earn a place in a respected sect',strength:8,intelligence:10,willpower:11}];
export const backgroundEventPool={baby:['You fall asleep to a lullaby while rain taps the shutters.','Your parents celebrate your birthday with a simple meal.','A neighbor brings a small cloth charm to bless your cradle.','You take your first uncertain steps across the courtyard.'],child:['You race other children along the irrigation channels.','A storyteller fills the square with tales of wandering sword masters.','You help your family prepare lanterns for the spring festival.','You discover a quiet place beneath a plum tree to read.','You watch a blacksmith hammer a glowing blade into shape.'],adult:['A caravan brings news of a distant sect tournament.','The village repairs its bridge after heavy summer rain.','The harvest festival brings music and bright lanterns to the streets.','An imperial messenger passes through without stopping.','A traveling physician offers advice in the market square.','Rumors of an ancient ruin spread through the tea houses.','Your neighbors gather to repair storm-damaged roofs.','You spend an evening reflecting on the people who shaped your path.']};
export const mainEventPool:Event[]=[{id:'lost-purse',title:'A purse in the dust',text:'A merchant drops a purse near your feet and disappears into the crowd.',choices:[{label:'Find its owner',hint:'+6 reputation',effect:{reputation:6}},{label:'Keep the silver',hint:'+14 silver · −5 reputation',effect:{silver:14,reputation:-5}},{label:'Leave it where it lies',hint:'Continue your day',effect:{}}]},{id:'festival',title:'A village celebration',text:'The village is preparing a lantern festival. The organizers ask whether you can lend a hand.',choices:[{label:'Help with preparations',hint:'+4 reputation · +4 health',effect:{reputation:4,health:4}},{label:'Donate to the feast',hint:'−8 silver · +8 reputation',effect:{silver:-8,reputation:8}},{label:'Enjoy a quiet evening',hint:'+6 health',effect:{health:6}}]},{id:'scroll',title:'A rain-soaked scroll',text:'You find a damaged martial scroll beneath the eaves of an abandoned shrine.',choices:[{label:'Study the surviving words',hint:'+16 qi',effect:{qi:16}},{label:'Sell it to a collector',hint:'+18 silver',effect:{silver:18}},{label:'Return it to the shrine',hint:'+5 reputation',effect:{reputation:5}}]}];
export function draw<T>(pool:readonly T[],r=Math.random):T{return pool[Math.floor(r()*pool.length)];}
export function randomName(r=Math.random){return draw(namePool.surnames,r)+' '+draw(namePool.given,r);}
